apiVersion: v1
kind: PersistentVolume
metadata:
  name: rpitemp-pv
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
  nfs:
    path: <MOUNT POINT>
    server: <NFS SERVER>